version: '3'

services:

  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-latest}
    container_name: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config/:/mosquitto/config
    ports:
      - 1883:1883