services:
  node-red-service:
    image: nodered/node-red
    container_name: node-red
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    networks:
      - broker-net
    ports:
      - "1881:1880"
    volumes:
      - ~/docker_volumes/vnodered:/data

  mqtt-broker-service:
    image: eclipse-mosquitto:1.6.13
    container_name: mqtt-broker
    restart: unless-stopped
    networks:
      - broker-net
    ports:
      - "1880:1880"

volumes:
  node-red-data:

networks:
  broker-net:
