version: '3.3'

services:
  mysqldb:
    image: mysql
    container_name: dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ~/docker_volumes/vmysql:/var/lib/mysql

  mongodb:
    image: mongo
    container_name: dev-mongo
    volumes:
      - ~/docker_volumes/vmongodb:/data/db
    ports:
      - "27017:27017"

  redisdb:
    image: redis
    container_name: dev-redis
    ports:
      - '6379:6379'

volumes:
  vmysql:
  vmongodb:

